# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12565e65a6849edb7ebeb701a616c1796fe3904f46c4ffac6d9b1792f00228e17ff013dc73403dd572bbecaee0828ef9f55e7ec1cd0161d80d6651cbc868afba

test:
  secret_key_base: fb8198a829c240f0beaa1685a7b37b8e820e14ea8397c68bed5bb937232a03050c9392d93252c53fa511745b3f5515828338c25375151a16a517fc05273cc7a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
